version: "3.1"
services:
  database:
    image: postgres:14.1-alpine3.15
    ports:
      - "15000:5432"
    environment:
      - "POSTGRES_DB=Dyshajobs"
      - "POSTGRES_USER=Dyshajobs"
      - "POSTGRES_PASSWORD=iamgroot"