#email: dysha237@gmail.com
#password: Dysha@0612

dyshajobs:
  admins: silatsamdylan@gmail.com
  leaders: willagropastoral@gmail.com
# Proxy pour les téléchargements de fichiers externes

spring:
  profiles:
    active: google
  datasource:
    username: dysha
    password: iamgroot
    url: jdbc:postgresql://localhost:5432/dysha
    #url: jdbc:postgresql://172.18.0.2/dysha

  flyway:
    create-schemas: true
    url: jdbc:postgresql://localhost:5432/dysha
    user: dysha
    password: iamgroot

  resources:
    chain:
      proxy:
        host: dysha
        port: 80

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    #host: localhost
    #port: 1025
    username: dysha237@gmail.com
    password: oboaeknjxqtyamoi
    protocol: smtp
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000


  logging:
    level:
      root: debug

  server:
    port: 80

  main:
      allow-bean-definition-overriding: true