#email: dysha237@gmail.com
#password: Dysha@0612
dysha:
  admins: silatsamdylan@gmail.com
  leaders: willagropastoral@gmail.com

# Proxy pour les téléchargements de fichiers externes

spring:
  datasource:
    username: dysha
    password: iamgroot
    url: jdbc:postgresql://localhost:15000/dysha

  profiles:
    active: google

  flyway:
    create-schemas: true
    url: jdbc:postgresql://localhost:15000/dysha
    user: dysha
    password: iamgroot
    locations: classpath:db/migration

  resources:
    chain:
      proxy:
        host: dysha
        port: 80

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: dysha237@gmail.com
    password: oboaeknjxqtyamoi
    protocol: smtp
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connection-timeout: 5000
          timeout: 3000
          write timeout: 5000

  logging:
    level:
      root: debug

  server:
    port: 80

  main:
      allow-bean-definition-overriding: true